PlayerScripts::PlayerStatus
ResourceType
const string CHANGE_METHOD_PREFIX
const string EVENT_NAME_SUFFIX
int _bombsHeld
readonly int [] POWER_LEVELS
readonly float [] MULTIPLIER_LEVELS
int maxHealth
int startingHealth
int maxBombsHeld
int startingBombsHeld
int maxPower
int startingPower
int maxMultiplierScoreBonus
Score gained for catching Multiplier pickups while at max multiplier.
Referenced by PlayerStatus.ChangeScoreMultiplier.
int healthUpRequirementIncrement
Amount of score required to gain extra health.
Referenced by PlayerStatus.ChangeScore, PlayerStatus.Reset.
int healthOverflowBonus
Score gained for gaining health while already at max health.
Referenced by PlayerStatus.ChangeHealth.
int _health
int _power
float _scoreMultiplier
int _scoreMultiplierLevel
int _healthUpRequirement
PlayerStatus Instance
Singleton instance of the PlayerStatus.
Referenced by PlayerStatus.ChangeResource, GameManager.SaveAndQuit.
int Score
ChangedValueListener HealthChangedEvent
ChangedValueListener BombsChangedEvent
ChangedValueListener PowerChangedEvent
ChangedValueListener PowerLevelChangedEvent
ChangedValueListener ScoreChangedEvent
ChangedValueListener ScoreMultiplierChangedEvent
Action GameOverEvent
Invoked when the player's health reaches less than 0.
Referenced by PlayerStatus.ChangeHealth.
delegate void ChangedValueListener(float value)
Method signature for events that are invoked upon a resource change.
void Reset()
Sets all resources to their starting values.
References PlayerStatus.healthUpRequirementIncrement.
void ChangeHealth(int amount)
Increases health. If health is already at max, increases score instead. When health reaches 0, invokes GameOverEvent.
amount Amount of health to be changed
References PlayerStatus.ChangeScore, PlayerStatus.GameOverEvent, PlayerStatus.healthOverflowBonus.
Referenced by PlayerStatus.ChangeScore.
void ChangeBombs(int amount)
Increases bombs held by a given amount.
amount
void ChangePower(int amount)
Increases power and changes power level if POWER_LEVELS requirement is met.
amount Amount of health to be changed
void ChangeScore(int amount)
Increases score, rewards extra health if requirement are met.
amount
References PlayerStatus.ChangeHealth, PlayerStatus.healthUpRequirementIncrement.
Referenced by PlayerStatus.ChangeHealth, PlayerStatus.ChangeScoreMultiplier.
void ChangeScoreMultiplier(int amount)
Changes score multiplier, awards bonus score if max multiplier is reached.
amount
References PlayerStatus.ChangeScore, PlayerStatus.maxMultiplierScoreBonus.
Referenced by PlayerStatus.ResetScoreMultiplier.
void ResetScoreMultiplier()
Sets Score Multiplier back to 1.
References PlayerStatus.ChangeScoreMultiplier.
void Start()
void OnDestroy()
static void Subscribe(ResourceType resourceType, ChangedValueListener listener)
Subscribes a listener to an appropriate resource change event.
resourceType Type of resource the listener subscribes to listener Method that responses to triggering of the appropriate event
static void ChangeResource(ResourceType resourceType, int amount)
Change a resource by a given amount.
resourceType Resource to change amount
References PlayerStatus.Instance.