PathCreation::Utility::CubicBezierUtility
static Vector3 EvaluateCurve(Vector3[] points, float t)
Returns point at time 't' (between 0 and 1) along bezier curve defined by 4 points (anchor_1, control_1, control_2, anchor_2)
References CubicBezierUtility.EvaluateCurve.
Referenced by CubicBezierUtility.EvaluateCurve.
static Vector3 EvaluateCurve(Vector3 a1, Vector3 c1, Vector3 c2, Vector3 a2, float t)
Returns point at time 't' (between 0 and 1) along bezier curve defined by 4 points (anchor_1, control_1, control_2, anchor_2)
static Vector3 EvaluateCurveDerivative(Vector3[] points, float t)
Returns a vector tangent to the point at time 't' This is the vector tangent to the curve at that point
References CubicBezierUtility.EvaluateCurveDerivative.
Referenced by CubicBezierUtility.EvaluateCurveDerivative, CubicBezierUtility.Normal.
static Vector3 EvaluateCurveDerivative(Vector3 a1, Vector3 c1, Vector3 c2, Vector3 a2, float t)
Calculates the derivative of the curve at time 't' This is the vector tangent to the curve at that point
static Vector3 EvaluateCurveSecondDerivative(Vector3[] points, float t)
Returns the second derivative of the curve at time 't'.
References CubicBezierUtility.EvaluateCurveSecondDerivative.
Referenced by CubicBezierUtility.EvaluateCurveSecondDerivative, CubicBezierUtility.Normal.
static Vector3 EvaluateCurveSecondDerivative(Vector3 a1, Vector3 c1, Vector3 c2, Vector3 a2, float t)
Returns the second derivative of the curve at time 't'.
static Vector3 Normal(Vector3[] points, float t)
Calculates the normal vector (vector perpendicular to the curve) at specified time.
References CubicBezierUtility.Normal.
Referenced by CubicBezierUtility.Normal.
static Vector3 Normal(Vector3 a1, Vector3 c1, Vector3 c2, Vector3 a2, float t)
Calculates the normal vector (vector perpendicular to the curve) at specified time.
References CubicBezierUtility.EvaluateCurveDerivative, CubicBezierUtility.EvaluateCurveSecondDerivative.
static Bounds CalculateSegmentBounds(Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3)
static Vector3[][] SplitCurve(Vector3[] points, float t)
Splits curve into two curves at time t. Returns 2 arrays of 4 points.
static float EstimateCurveLength(Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3)
static List< float > ExtremePointTimes(Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3)
Times of stationary points on curve (points where derivative is zero on any axis)
static IEnumerable< float > StationaryPointTimes(float a, float b, float c)