Serialization::ScoreData
const string SAVE_PATH
const int MAX_SAVED_SCORES
const int AUTHORS_PB
const string AUTHOR
string [] names
Setters of the scores sorted by score achieved.
Referenced by ScoreData.AddScore.
int [] sortedScores
Highest achieved scores sorted from highest to lowest.
Referenced by ScoreData.AddScore.
int savedScoresCount
Number of saved scores.
Referenced by ScoreData.AddScore.
static ScoreData LoadScores()
Loads data from the scores save file. Create a new save file if it doesn't exist.
Object with values retrieved from the scores save file
Referenced by GameManager.SaveAndQuit.
void AddScore(int score, string name)
Checks if the score is high enough to be saved and adds it to the array of scores in the correct position. If yes the score at the lowest position will be lost!
score Score achieved name Setter of the score
References ScoreData.names, ScoreData.savedScoresCount, ScoreData.sortedScores.
Referenced by ScoreData.AddScoreAndSave.
void AddScoreAndSave(int score, string name)
Checks if the score is high enough to be saved and adds it to the array of scores in the correct position. If yes the score at the lowest position will be lost! Then the data are saved to the scores save file.
score Achieved score name Setter of the score
References ScoreData.AddScore.
Referenced by GameManager.SaveAndQuit.