PathCreation::BezierPath
ControlMode
System.Action OnModified
List<Vector3> points
bool isClosed
PathSpace space
ControlMode controlMode
float autoControlLength
bool boundsUpToDate
Bounds bounds
List<float> perAnchorNormalsAngle
float globalNormalsAngle
bool flipNormals
Vector3 this[int i]
Get world space position of point.
int NumPoints
Total number of points in the path (anchors and controls)
Referenced by BezierPath.UpdateToNewPathSpace.
int NumAnchorPoints
Number of anchor points making up the path.
Referenced by BezierPath.AutoSetAllControlPoints, BezierPath.AutoSetStartAndEndControls.
int NumSegments
Number of bezier curves making up this path.
Referenced by BezierPath.CalculateBoundsWithTransform, BezierPath.DeleteSegment, BezierPath.GetPointsInSegment, BezierPath.UpdateBounds.
PathSpace Space
Path can exist in 3D (xyz), 2D (xy), or Top-Down (xz) space In xy or xz space, points will be clamped to that plane (so in a 2D path, for example, points will always be at 0 on z axis)
Referenced by BezierPath.BezierPath, VertexPath.VertexPath.
bool IsClosed
If closed, path will loop back from end point to start point.
Referenced by BezierPath.BezierPath, VertexPath.VertexPath.
ControlMode ControlPointMode
The control mode determines the behaviour of control points. Possible modes are: Aligned = controls stay in straight line around their anchor Mirrored = controls stay in straight, equidistant line around their anchor Free = no constraints (use this if sharp corners are needed) Automatic = controls placed automatically to try make the path smooth
float AutoControlLength
When using automatic control point placement, this value scales how far apart controls are placed.
bool FlipNormals
Flip the normal vectors 180 degrees.
Referenced by VertexPath.VertexPath.
float GlobalNormalsAngle
Global angle that all normal vectors are rotated by (only relevant for paths in 3D space)
Referenced by VertexPath.VertexPath.
Bounds PathBounds
Bounding box containing the path.
Referenced by BezierPath.UpdateToNewPathSpace.
BezierPath(Vector3 centre, bool isClosed=false, PathSpace space=PathSpace.xyz)
Creates a two-anchor path centred around the given centre point.
param name="isClosed"> Should the end point connect back to the start point? param name="space"> Determines if the path is in 3d space, or clamped to the xy/xz plane
References BezierPath.IsClosed, BezierPath.Space.
BezierPath(IEnumerable< Vector3 > points, bool isClosed=false, PathSpace space=PathSpace.xyz)
Creates a path from the supplied 3D points.
param name="points"> List or array of points to create the path from. param name="isClosed"> Should the end point connect back to the start point? param name="space"> Determines if the path is in 3d space, or clamped to the xy/xz plane
References BezierPath.AddSegmentToEnd.
BezierPath(IEnumerable< Vector2 > transforms, bool isClosed=false, PathSpace space=PathSpace.xy)
Creates a path from the positions of the supplied 2D points.
param name="transforms"> List or array of transforms to create the path from. param name="isClosed"> Should the end point connect back to the start point? param name="space"> Determines if the path is in 3d space, or clamped to the xy/xz plane
BezierPath(IEnumerable< Transform > transforms, bool isClosed=false, PathSpace space=PathSpace.xy)
Creates a path from the positions of the supplied transforms.
param name="transforms"> List or array of transforms to create the path from. param name="isClosed"> Should the end point connect back to the start point? param name="space"> Determines if the path is in 3d space, or clamped to the xy/xz plane
BezierPath(IEnumerable< Vector2 > points, PathSpace space=PathSpace.xyz, bool isClosed=false)
Creates a path from the supplied 2D points.
param name="points"> List or array of 2d points to create the path from. param name="isClosed"> Should the end point connect back to the start point? param name="pathSpace"> Determines if the path is in 3d space, or clamped to the xy/xz plane
Vector3 GetPoint(int i)
Get world space position of point.
void SetPoint(int i, Vector3 localPosition, bool suppressPathModifiedEvent=false)
Get world space position of point.
void AddSegmentToEnd(Vector3 anchorPos)
Add new anchor point to end of the path.
References BezierPath.AutoSetAllAffectedControlPoints.
Referenced by BezierPath.BezierPath.
void AddSegmentToStart(Vector3 anchorPos)
Add new anchor point to start of the path.
References BezierPath.AutoSetAllAffectedControlPoints.
void SplitSegment(Vector3 anchorPos, int segmentIndex, float splitTime)
Insert new anchor point at given position. Automatically place control points around it so as to keep shape of curve the same.
References BezierPath.AutoSetAllAffectedControlPoints, BezierPath.GetPointsInSegment, BezierPath.MovePoint.
void DeleteSegment(int anchorIndex)
Delete the anchor point at given index, as well as its associated control points.
References BezierPath.AutoSetAllControlPoints, BezierPath.NumSegments.
Vector3[] GetPointsInSegment(int segmentIndex)
Returns an array of the 4 points making up the segment (anchor1, control1, control2, anchor2)
References BezierPath.LoopIndex, BezierPath.NumSegments.
Referenced by BezierPath.CalculateBoundsWithTransform, BezierPath.SplitSegment, BezierPath.UpdateBounds.
void MovePoint(int i, Vector3 pointPos, bool suppressPathModifiedEvent=false)
Move an existing point to a new position.
References BezierPath.AutoSetAllAffectedControlPoints, BezierPath.LoopIndex.
Referenced by BezierPath.SplitSegment.
Bounds CalculateBoundsWithTransform(Transform transform)
Update the bounding box of the path.
References BezierPath.GetPointsInSegment, BezierPath.NumSegments.
float GetAnchorNormalAngle(int anchorIndex)
Get the desired angle of the normal vector at a particular anchor (only relevant for paths in 3D space)
void SetAnchorNormalAngle(int anchorIndex, float angle)
Set the desired angle of the normal vector at a particular anchor (only relevant for paths in 3D space)
void ResetNormalAngles()
Reset global and anchor normal angles to 0.
void NotifyPathModified()
void UpdateBounds()
Update the bounding box of the path.
References BezierPath.GetPointsInSegment, BezierPath.NumSegments.
void AutoSetAllAffectedControlPoints(int updatedAnchorIndex)
Determines good positions (for a smooth path) for the control points affected by a moved/inserted anchor point.
References BezierPath.AutoSetAnchorControlPoints, BezierPath.AutoSetStartAndEndControls, BezierPath.LoopIndex.
Referenced by BezierPath.AddSegmentToEnd, BezierPath.AddSegmentToStart, BezierPath.MovePoint, BezierPath.SplitSegment.
void AutoSetAllControlPoints()
Determines good positions (for a smooth path) for all control points.
References BezierPath.AutoSetAnchorControlPoints, BezierPath.AutoSetStartAndEndControls, BezierPath.NumAnchorPoints.
Referenced by BezierPath.DeleteSegment.
void AutoSetAnchorControlPoints(int anchorIndex)
Calculates good positions (to result in smooth path) for the controls around specified anchor.
References BezierPath.LoopIndex.
Referenced by BezierPath.AutoSetAllAffectedControlPoints, BezierPath.AutoSetAllControlPoints, BezierPath.AutoSetStartAndEndControls.
void AutoSetStartAndEndControls()
Determines good positions (for a smooth path) for the control points at the start and end of a path.
References BezierPath.AutoSetAnchorControlPoints, BezierPath.NumAnchorPoints.
Referenced by BezierPath.AutoSetAllAffectedControlPoints, BezierPath.AutoSetAllControlPoints, BezierPath.UpdateClosedState.
void UpdateToNewPathSpace(PathSpace previousSpace)
Update point positions for new path space (for example, if changing from xy to xz path, y and z axes will be swapped so the path keeps its shape in the new space)
References BezierPath.NumPoints, BezierPath.PathBounds.
void UpdateClosedState()
Add/remove the extra 2 controls required for a closed path.
References BezierPath.AutoSetStartAndEndControls.
int LoopIndex(int i)
Loop index around to start/end of points array if out of bounds (useful when working with closed paths)
Referenced by BezierPath.AutoSetAllAffectedControlPoints, BezierPath.AutoSetAnchorControlPoints, BezierPath.GetPointsInSegment, BezierPath.MovePoint.