PathCreation::VertexPath
readonly PathSpace space
readonly bool isClosedLoop
readonly Vector3 [] localPoints
readonly Vector3 [] localTangents
readonly Vector3 [] localNormals
readonly float [] times
Percentage along the path at each vertex (0 being start of path, and 1 being the end)
Referenced by VertexPath.CalculatePercentOnPathData, VertexPath.GetClosestTimeOnPath, VertexPath.VertexPath.
readonly float length
Total distance between the vertices of the polyline.
Referenced by VertexPath.GetDirectionAtDistance, VertexPath.GetNormalAtDistance, VertexPath.GetPointAtDistance, VertexPath.GetRotationAtDistance, VertexPath.VertexPath.
readonly float [] cumulativeLengthAtEachVertex
Total distance from the first vertex up to each vertex in the polyline.
Referenced by VertexPath.GetClosestDistanceAlongPath, VertexPath.VertexPath.
readonly Bounds bounds
Bounding box of the path.
Referenced by VertexPath.VertexPath.
readonly Vector3 up
Equal to (0,0,-1) for 2D paths, and (0,1,0) for XZ paths.
Referenced by VertexPath.VertexPath.
const int accuracy
const float minVertexSpacing
Transform transform
int NumPoints
VertexPath(BezierPath bezierPath, Transform transform, float maxAngleError=0.3f, float minVertexDst=0)
Splits bezier path into array of vertices along the path.
param name="maxAngleError">How much can the angle of the path change before a vertex is added. This allows fewer vertices to be generated in straighter sections. param name="minVertexDst">Vertices won't be added closer together than this distance, regardless of angle error.
VertexPath(BezierPath bezierPath, Transform transform, float vertexSpacing)
Splits bezier path into array of vertices along the path.
param name="maxAngleError">How much can the angle of the path change before a vertex is added. This allows fewer vertices to be generated in straighter sections. param name="minVertexDst">Vertices won't be added closer together than this distance, regardless of angle error. param name="accuracy">Higher value means the change in angle is checked more frequently.
void UpdateTransform(Transform transform)
Vector3 GetTangent(int index)
Vector3 GetNormal(int index)
Vector3 GetPoint(int index)
Vector3 GetPointAtDistance(float dst, EndOfPathInstruction endOfPathInstruction=EndOfPathInstruction.Loop)
Gets point on path based on distance travelled.
References VertexPath.GetPointAtTime, VertexPath.length.
Vector3 GetDirectionAtDistance(float dst, EndOfPathInstruction endOfPathInstruction=EndOfPathInstruction.Loop)
Gets forward direction on path based on distance travelled.
References VertexPath.GetDirection, VertexPath.length.
Vector3 GetNormalAtDistance(float dst, EndOfPathInstruction endOfPathInstruction=EndOfPathInstruction.Loop)
Gets normal vector on path based on distance travelled.
References VertexPath.length.
Quaternion GetRotationAtDistance(float dst, EndOfPathInstruction endOfPathInstruction=EndOfPathInstruction.Loop)
Gets a rotation that will orient an object in the direction of the path at this point, with local up point along the path's normal.
References VertexPath.GetRotation, VertexPath.length.
Vector3 GetPointAtTime(float t, EndOfPathInstruction endOfPathInstruction=EndOfPathInstruction.Loop)
Gets point on path based on 'time' (where 0 is start, and 1 is end of path).
References VertexPath.CalculatePercentOnPathData.
Referenced by VertexPath.GetPointAtDistance.
Vector3 GetDirection(float t, EndOfPathInstruction endOfPathInstruction=EndOfPathInstruction.Loop)
Gets forward direction on path based on 'time' (where 0 is start, and 1 is end of path).
References VertexPath.CalculatePercentOnPathData.
Referenced by VertexPath.GetDirectionAtDistance.
Vector3 GetNormal(float t, EndOfPathInstruction endOfPathInstruction=EndOfPathInstruction.Loop)
Gets normal vector on path based on 'time' (where 0 is start, and 1 is end of path).
References VertexPath.CalculatePercentOnPathData.
Quaternion GetRotation(float t, EndOfPathInstruction endOfPathInstruction=EndOfPathInstruction.Loop)
Gets a rotation that will orient an object in the direction of the path at this point, with local up point along the path's normal.
References VertexPath.CalculatePercentOnPathData.
Referenced by VertexPath.GetRotationAtDistance.
Vector3 GetClosestPointOnPath(Vector3 worldPoint)
Finds the closest point on the path from any point in the world.
References VertexPath.CalculateClosestPointOnPathData.
float GetClosestTimeOnPath(Vector3 worldPoint)
Finds the 'time' (0=start of path, 1=end of path) along the path that is closest to the given point.
References VertexPath.CalculateClosestPointOnPathData, VertexPath.times.
float GetClosestDistanceAlongPath(Vector3 worldPoint)
Finds the distance along the path that is closest to the given point.
References VertexPath.CalculateClosestPointOnPathData, VertexPath.cumulativeLengthAtEachVertex.
VertexPath(BezierPath bezierPath, VertexPathUtility.PathSplitData pathSplitData, Transform transform)
Internal contructor.
References VertexPath.bounds, VertexPath.cumulativeLengthAtEachVertex, BezierPath.FlipNormals, BezierPath.GlobalNormalsAngle, BezierPath.IsClosed, VertexPath.length, BezierPath.Space, VertexPath.times, VertexPath.up.
TimeOnPathData CalculatePercentOnPathData(float t, EndOfPathInstruction endOfPathInstruction)
For a given value 't' between 0 and 1, calculate the indices of the two vertices before and after t. Also calculate how far t is between those two vertices as a percentage between 0 and 1.
References VertexPath.times.
Referenced by VertexPath.GetDirection, VertexPath.GetNormal, VertexPath.GetPointAtTime, VertexPath.GetRotation.
TimeOnPathData CalculateClosestPointOnPathData(Vector3 worldPoint)
Calculate time data for closest point on the path from given world point.
Referenced by VertexPath.GetClosestDistanceAlongPath, VertexPath.GetClosestPointOnPath, VertexPath.GetClosestTimeOnPath.